[build]
  publish = "public"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  # Inclure node-fetch dans le déploiement de la fonction
  included_files = ["node_modules/node-fetch/**"]
