[build]
  publish = "public"
  command = "npm install"
  edge_functions = "netlify/edge-functions"

[functions]
  directory = "netlify/functions"
  # Inclure node-fetch dans le déploiement de la fonction
  included_files = ["node_modules/node-fetch/**"]

[[edge_functions]]
  # Ceci définit l'URL qui déclenchera votre fonction.
  # Par exemple : https://monsite.com/telecharger-episode
  path = "/telecharger-episode"
  
  # Ceci est le nom du fichier de votre fonction.
  function = "download-stream"